version: '3.9'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - db

  chatbot:
    container_name: chatbot
    build: .
    restart: always
    command: python3 -u llm.py
    volumes:
      - ./models:/models  # Монтируйте папку с моделями внутрь контейнера
      - ./chroma:/chroma
      - ./upload_files:/upload_files
      - ./scripts:/app
      - ./logging/:/logging
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    ports:
      - "7860:7860"
    networks:
      - db

  worker:
    container_name: worker
    build: ./
    restart: always
    command: celery -A app worker -l info -E
    volumes:
      - ./scripts:/data
      - ./models:/models  # Монтируйте папку с моделями внутрь контейнера
      - ./chroma:/chroma
      - ./upload_files:/upload_files
      - ./logging/:/logging
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
      PYTHONPATH: /data
      C_FORCE_ROOT: "yes"
    ports:
      - "7861:7861"
    depends_on:
      - redis
    networks:
      - db

  flower:
    image: mher/flower:0.9.7
    container_name: flower
    command: [ 'flower', '--broker=redis://redis', '--port=5555' ]
    restart: always
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - db

networks:
  db:
    driver: bridge