version: '3.9'
services:
  clickhouse:
    image: bitnami/clickhouse:22.11.2
    container_name: clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse:/bitnami/clickhouse
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_HTTP_PORT=8123
    networks:
      - db

  chroma:
    image: chromadb/chroma:0.4.18
    container_name: chroma
    restart: always
    volumes:
      - ./chroma:/chroma/chroma
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
    ports:
      - "8000:8000"
    depends_on:
      - clickhouse
    networks:
      - db

networks:
  db:
    driver: bridge