version: '3.9'
services:
  chatbot:
    container_name: chatbot
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    restart: always
    volumes:
      - ./models:/models  # Монтируйте папку с моделями внутрь контейнера
      - ./chroma:/chroma
      - ./upload_files:/upload_files
      - ./scripts:/app
    ports:
      - "8001:8080"
    networks:
      - db

networks:
  db:
    driver: bridge